// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKoVZzzHy6LBevRokY-6xpgk286jXMJy8',
    appId: '1:621798469036:web:06e339bd9c02d4fdd1de09',
    messagingSenderId: '621798469036',
    projectId: 'proyectomonotributo',
    authDomain: 'proyectomonotributo.firebaseapp.com',
    storageBucket: 'proyectomonotributo.firebasestorage.app',
    measurementId: 'G-3MN0V7G2KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbEmRiYHdlAwzuMhiwe0-wHkXqA4ApQU',
    appId: '1:621798469036:android:aa28897aa45a66d3d1de09',
    messagingSenderId: '621798469036',
    projectId: 'proyectomonotributo',
    storageBucket: 'proyectomonotributo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdv3a7izz3IuUPze3FsUPaFcQvYhPWTUM',
    appId: '1:621798469036:ios:6d908d0e066e9610d1de09',
    messagingSenderId: '621798469036',
    projectId: 'proyectomonotributo',
    storageBucket: 'proyectomonotributo.firebasestorage.app',
    iosBundleId: 'com.example.argestionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdv3a7izz3IuUPze3FsUPaFcQvYhPWTUM',
    appId: '1:621798469036:ios:6d908d0e066e9610d1de09',
    messagingSenderId: '621798469036',
    projectId: 'proyectomonotributo',
    storageBucket: 'proyectomonotributo.firebasestorage.app',
    iosBundleId: 'com.example.argestionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKoVZzzHy6LBevRokY-6xpgk286jXMJy8',
    appId: '1:621798469036:web:d423a490dc5d1ed9d1de09',
    messagingSenderId: '621798469036',
    projectId: 'proyectomonotributo',
    authDomain: 'proyectomonotributo.firebaseapp.com',
    storageBucket: 'proyectomonotributo.firebasestorage.app',
    measurementId: 'G-PR6BTEMS3E',
  );
}
